include:
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
      - kaniko-ci.yml
    ref: main

# default:
#  tags:
#    - ADD_CUSTOM_TAG_HERE

cache:
  paths:
    - .m2/repository/
    - node_modules

variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  DOCKERFILE: Dockerfile
  REGISTRY_URL: "${IMAGE_REPOSITORY}"

stages:
  - read-secret
  - test-app
  - docker-build

read_secret:
  only:
    - web
  stage: read-secret
  extends:
    - .vault:read_secret

docker-build:
  only:
    - web
  variables:
    WORKING_DIR: "."
    IMAGE_NAME: s3-test
  stage: docker-build
  extends:
    - .kaniko:simple-build-push