apiVersion: apps/v1
kind: Deployment
metadata:
  name: tests3
  labels:
    app: tests3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tests3
  template:
    metadata:
      labels:
        app: tests3
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- if .Values.randomFile }}
      initContainers:
        - name: random-file
          image: "alpine:latest"
          imagePullPolicy: Always
          env:
            - name: FILE_TO_UPLOAD
              value: "{{ .Values.FILE_TO_UPLOAD }}"
          command: ["sh", "-c", "dd if=/dev/urandom of={{ .Values.FILE_TO_UPLOAD }} bs={{ .Values.FILE_SIZE }} count=16 iflag=fullblock"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: test-volume
              mountPath: /tmp
      {{- end }}
      containers:
        - name: tests3
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: APP_S3_ENDPOINT
              value: "{{ .Values.APP_S3_ENDPOINT }}"
            - name: APP_S3_REGION
              value: "{{ .Values.APP_S3_REGION }}"
            - name: AWS_ACCESS_KEY_ID
              value: "{{ .Values.AWS_ACCESS_KEY_ID }}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ .Values.AWS_SECRET_ACCESS_KEY }}"
            - name: APP_S3_FILE_TO_UPLOAD
              value: "{{ .Values.FILE_TO_UPLOAD }}"
            - name: DISABLE_CERT_CHECKING_SYSTEM_PROPERTY
              value: "{{ .Values.DISABLE_CERT_CHECKING_SYSTEM_PROPERTY }}"
            - name: APP_S3_BUCKET
              value: "{{ .Values.APP_S3_BUCKET }}"
          envFrom:
            - configMapRef:
                name: tests3
          volumeMounts:
            - name: test-volume
              mountPath: /tmp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: test-volume
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi